# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  config.vm.hostname = "manager-node"
  config.vm.network "public_network", ip: "192.168.1.100", bridge: "Realtek PCIe GbE Family Controller"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 2048
    v.cpus = 1  
  end
end
